const subjects = [
  { name: "Mathematics-I", icon: "∑", progress: 60, meta: "Study queue // source required", topics: ["Differential calculus", "Integral calculus", "Matrices", "Coordinate geometry"], query: "BTEUP Polytechnic Mathematics 1 Hindi" },
  { name: "Chemistry", icon: "⚗", progress: 40, meta: "Study queue // source required", topics: ["Atomic structure", "Chemical bonding", "Water technology", "Corrosion"], query: "BTEUP Polytechnic Chemistry Hindi" },
  { name: "Physics", icon: "λ", progress: 30, meta: "Study queue // source required", topics: ["Units and dimensions", "Motion", "Work and energy", "Electricity"], query: "BTEUP Polytechnic Physics Hindi" },
  { name: "Communication Skills", icon: "Aa", progress: 70, meta: "Study queue // source required", topics: ["Grammar", "Vocabulary", "Writing formats", "Communication"], query: "Polytechnic Communication Skills Hindi English" }
];
const topicLabels = {
  "Differential calculus": "अवकलन गणित",
  "Integral calculus": "समाकलन गणित",
  "Matrices": "आव्यूह",
  "Coordinate geometry": "निर्देशांक ज्यामिति",
  "Atomic structure": "परमाणु संरचना",
  "Chemical bonding": "रासायनिक बंधन",
  "Water technology": "जल प्रौद्योगिकी",
  "Corrosion": "संक्षारण",
  "Units and dimensions": "मात्रक और विमाएँ",
  "Motion": "गति",
  "Work and energy": "कार्य और ऊर्जा",
  "Electricity": "विद्युत",
  "Grammar": "व्याकरण",
  "Vocabulary": "शब्दावली",
  "Writing formats": "लेखन प्रारूप",
  "Communication": "संचार"
};
function topicLabel(topic) { return topicLabels[topic] || topic; }
const careerSteps = ["C Fundamentals", "Python Fundamentals", "Git + GitHub", "SQL + DBMS", "HTML + CSS", "JavaScript", "Flask / Django", "REST APIs", "DSA alongside", "Backend Projects", "AI APIs", "AI Projects", "Internship Prep", "Job Preparation", "B.Tech + Growth"];
const careerLevels = careerSteps.map((name, index) => ({
  name,
  prerequisite: index === 0 ? "None" : careerSteps[index - 1],
  alongside: index === 8 ? "Runs alongside development; it never blocks projects." : ""
}));
const pythonLessons = ["What is Python?", "Variables and data types", "Input and output", "Operators", "if / else", "Loops", "Lists", "Tuples and dictionaries", "Functions", "Modules", "File handling", "Exceptions", "OOP basics", "Mini project", "Checkpoint"];
const careerLessons = [
  { title: "What is Python?", learn: "Python is a readable programming language used to automate tasks, build APIs, and connect applications to data.", why: "A clear mental model of Python makes every later backend lesson easier.", example: "A variable can store a learner's name: name = 'Asha'.", code: "name = 'Asha'\\nprint(f'Hello, {name}!')", practice: ["Print your name.", "Store your goal in a variable.", "Print a sentence using an f-string."], task: "Create a three-line introduction program.", next: "Variables and data types." },
  { title: "Variables and data types", learn: "Variables label values. Common beginner types are strings, integers, floats, and booleans.", why: "Web requests and database rows are made of typed values.", example: "age = 19 stores an integer; name = 'Asha' stores text.", code: "age = 19\\nready = True\\nprint(age, ready)", practice: ["Create a float for your study hours.", "Check a value's type.", "Convert a string number to int."], task: "Build a profile card using four variables.", next: "Input and output." },
  { title: "Input and output", learn: "input() receives text from a user and print() displays a result.", why: "Backend services receive input and return useful output.", example: "A study timer asks for minutes, then displays the session.", code: "minutes = int(input('Minutes: '))\\nprint(f'Study for {minutes} minutes.')", practice: ["Ask for a subject.", "Ask for minutes and add 5.", "Print a formatted summary."], task: "Build a command-line study target form.", next: "Operators." },
  { title: "Operators", learn: "Operators calculate, compare, and combine values.", why: "Conditions, scores, and API data all require correct calculations.", example: "total = completed / lessons * 100 calculates progress.", code: "completed = 4\\nlessons = 10\\nprint(completed / lessons * 100)", practice: ["Calculate weekly minutes.", "Compare two scores.", "Use % to find a remainder."], task: "Calculate your completion percentage.", next: "if / else." },
  { title: "if / else", learn: "Conditions let a program choose a path when a statement is true or false.", why: "Real applications must respond differently to valid, invalid, and missing input.", example: "Show a revision reminder when accuracy is below 70%.", code: "accuracy = 65\\nif accuracy < 70:\\n    print('Revise this topic')\\nelse:\\n    print('Move forward')", practice: ["Check if study time is enough.", "Classify a score.", "Handle an empty name."], task: "Create a simple readiness checker.", next: "Loops." },
  { title: "Loops", learn: "Loops repeat work without copying the same code.", why: "You will loop through lessons, database rows, and API results.", example: "for topic in topics processes each topic once.", code: "topics = ['loops', 'lists', 'functions']\\nfor topic in topics:\\n    print(topic)", practice: ["Print numbers 1–10.", "Loop through your subjects.", "Add a total with a loop."], task: "Print a five-item revision checklist.", next: "Lists." },
  { title: "Lists", learn: "Lists hold an ordered collection of values.", why: "Most application data begins as collections: tasks, users, or messages.", example: "lessons[0] accesses the first lesson.", code: "lessons = ['Python', 'SQL']\\nlessons.append('Flask')\\nprint(lessons)", practice: ["Create and append a list.", "Remove an item.", "Loop through a list."], task: "Build a list-based task tracker.", next: "Tuples and dictionaries." },
  { title: "Tuples and dictionaries", learn: "Tuples group fixed values; dictionaries map readable keys to values.", why: "Dictionaries closely resemble JSON returned by APIs.", example: "profile['goal'] retrieves one field.", code: "profile = {'name': 'Asha', 'goal': 'backend'}\\nprint(profile['goal'])", practice: ["Create a profile dictionary.", "Update a value.", "Loop over key-value pairs."], task: "Represent one project as a dictionary.", next: "Functions." },
  { title: "Functions", learn: "Functions package a repeatable operation behind a clear name.", why: "Backend code stays testable and maintainable when behavior is separated into functions.", example: "A function can calculate a progress percentage.", code: "def progress(done, total):\\n    return done / total * 100\\nprint(progress(4, 10))", practice: ["Write a greeting function.", "Add two numbers.", "Return a readiness label."], task: "Create three tested study helper functions.", next: "Modules." },
  { title: "Modules", learn: "Modules split related code into reusable files.", why: "Every practical backend project needs organized modules.", example: "from helpers import progress imports one function.", code: "# helpers.py\\ndef add(a, b):\\n    return a + b\\n\\n# main.py\\nfrom helpers import add", practice: ["Create a helpers file.", "Import one function.", "Use the standard math module."], task: "Split your task tracker into two files.", next: "File handling." },
  { title: "File handling", learn: "Python can read and write files for local persistence.", why: "Before a database, files teach you how applications store state safely.", example: "JSON can store progress between sessions.", code: "with open('notes.txt', 'w') as file:\\n    file.write('Revise functions')", practice: ["Write a note.", "Read it back.", "Handle a missing file."], task: "Persist your study checklist to a text file.", next: "Exceptions." },
  { title: "Exceptions", learn: "Exceptions are signals that something unexpected happened.", why: "Robust APIs must handle bad input and unavailable services without crashing.", example: "Catch invalid numeric input and ask again.", code: "try:\\n    minutes = int(input('Minutes: '))\\nexcept ValueError:\\n    print('Enter a whole number.')", practice: ["Catch ValueError.", "Use finally.", "Raise a useful error."], task: "Make your timer reject invalid input.", next: "OOP basics." },
  { title: "OOP basics", learn: "Classes group data and behavior into a reusable object.", why: "Frameworks and larger backend codebases use objects to model domain behavior.", example: "A StudySession can own minutes and a finish method.", code: "class StudySession:\\n    def __init__(self, minutes):\\n        self.minutes = minutes", practice: ["Create a class.", "Add a method.", "Instantiate two objects."], task: "Model a project with a class.", next: "Mini project." },
  { title: "Mini project", learn: "Combine your Python fundamentals into a small, complete application.", why: "Building reveals gaps that passive lessons hide.", example: "A CLI study tracker can store tasks, show progress, and save notes.", code: "tasks = []\\n# add, list, complete, and save tasks", practice: ["Add a feature.", "Handle bad input.", "Write a README."], task: "Finish a CLI Study Timer and publish it privately first.", next: "Python checkpoint." },
  { title: "Checkpoint", learn: "A checkpoint tests practical ability, not memory.", why: "Learned is not practiced, and practiced is not mastered.", example: "Solve a new problem without copying a tutorial.", code: "# Build a function that reads a list of scores and returns accuracy.", practice: ["Write functions.", "Use dictionaries.", "Read/write files.", "Handle an exception."], task: "Complete the Python checkpoint in the Practice section.", next: "Git + GitHub basics." }
];
const careerProjects = [
  { name: "CLI Study Timer", difficulty: "VERY EASY", skills: "variables, loops, functions, files", purpose: "Track focused study sessions from a terminal.", features: "Start timer, save sessions, show streak, export summary.", folder: "study-timer/\\n  main.py\\n  storage.py\\n  README.md", next: "Add tests for time calculations." },
  { name: "Expense Tracker", difficulty: "EASY", skills: "Python, JSON, validation, Git", purpose: "Record and summarize personal expenses.", features: "Add, list, filter, monthly totals, invalid-input handling.", folder: "expense-tracker/\\n  app.py\\n  data.json\\n  tests/", next: "Replace JSON storage with SQLite." },
  { name: "Expense Tracker API", difficulty: "INTERMEDIATE", skills: "Flask, HTTP, REST, SQLite", purpose: "Expose your tracker through a documented API.", features: "CRUD routes, status codes, validation, API README.", folder: "expense-api/\\n  app.py\\n  routes/\\n  tests/\\n  README.md", next: "Add authentication and deployment." },
  { name: "AI Study Planner API", difficulty: "ADVANCED", skills: "Backend, JSON, authentication, AI API integration", purpose: "Add a safely handled AI suggestion endpoint to a backend you already understand.", features: "API-key protection, prompt validation, timeout handling, clear errors.", folder: "ai-study-planner/\\n  app.py\\n  services/\\n  tests/\\n  README.md", next: "Measure response quality and add human review." }
];
const questions = [
  { question: "Which keyword defines a function in Python?", answer: "def", hint: "It is a short keyword beginning with d.", explanation: "Python uses def followed by the function name and parentheses." },
  { question: "What is the derivative of x²?", answer: "2x", hint: "Use the power rule: n·x^(n−1).", explanation: "For xⁿ, the derivative is n·x^(n−1), so x² becomes 2x." },
  { question: "What unit measures electric current?", answer: "ampere", hint: "It is named after a French physicist.", explanation: "Electric current is measured in amperes (A)." }
];
const examAnswers = { "Differential calculus":"2x", "Integral calculus":"x²/2+c", "Matrices":"row", "Coordinate geometry":"0,0", "Atomic structure":"protons", "Chemical bonding":"covalent", "Water technology":"calcium magnesium", "Corrosion":"rusting", "Units and dimensions":"newton", "Motion":"direction", "Work and energy":"joule", "Electricity":"ampere", "Grammar":"writes", "Vocabulary":"glad", "Writing formats":"subject", "Communication":"feedback" };
const defaultState = { view: "home", xp: 0, checked: [], careerDone: 0, completedLessons: [], revision: [], examTopics: {}, settings: { language: "Hinglish", dailyTime: "2 hours", goal: "Python Backend Developer", examDate: "", sound: false }, stats: { solved: 0, correct: 0, weak: [], practiceMinutes: 0 }, projectMilestones: 0, subject: null, topic: null };
const saved = localStorage.getItem("studyOSState");
const parsedState = saved ? JSON.parse(saved) : null;
const state = parsedState ? { ...defaultState, ...parsedState, settings: { ...defaultState.settings, ...(parsedState.settings || {}) }, stats: { ...defaultState.stats, ...(parsedState.stats || {}) } } : structuredClone(defaultState);
function save() { localStorage.setItem("studyOSState", JSON.stringify(state)); }
function topicKey(subject, topic) { return `${subject}::${topic}`; }
function topicStatus(subject, topic) { return state.examTopics?.[topicKey(subject, topic)] || { learned:false, practiced:false, tested:false }; }
function subjectProgress(subject) { const score = subject.topics.reduce((total, topic) => { const s = topicStatus(subject.name, topic); return total + (s.tested ? 1 : s.practiced ? .65 : s.learned ? .3 : 0); }, 0); return Math.round(score / subject.topics.length * 100); }
function nextExamMission() { for (const subject of subjects) { const topic = subject.topics.find(item => !topicStatus(subject.name, item).tested); if (topic) return { subject: subject.name, topic }; } return { subject: subjects[0].name, topic: subjects[0].topics[0] }; }
function renderExamTopic(subjectName, topic) {
  const subject = subjects.find(s => s.name === subjectName); const status = topicStatus(subjectName, topic);
    const chapter = topicLabel(topic);
  const simple = `Study ${chapter} step by step. Read the basic idea first, then follow the example and solve one question yourself.`;
  const definition = subjectName === "Mathematics-I" ? `${chapter} is a mathematics concept where rules and formulas are used to solve problems.` : subjectName === "Physics" ? `${chapter} explains a physical event using quantity, direction, and SI units.` : subjectName === "Chemistry" ? `${chapter} explains the structure, properties, or changes of matter.` : `${chapter} helps you express ideas clearly and correctly.`;
  const formula = subjectName === "Mathematics-I" ? "Do not only memorize the formula. Understand each symbol, substitute the values, and check the answer." : subjectName === "Physics" ? "Revise the quantity, formula, and SI unit together." : subjectName === "Chemistry" ? "Revise the definition, cause, chemical equation, and one daily-life example together." : "Read the rule and apply it in one short, clear sentence.";
  const question = topic === "Differential calculus" ? "What is the derivative of x²?" : topic === "Integral calculus" ? "What is the integral of ∫x dx?" : `Write the most important definition of ${chapter}.`;
  return layout(`${subjectName} // ${chapter}`, "Topic → notes → practice → test → revision. Opening this page does not mark the topic complete.", `<button class="btn secondary" data-action="back-subject">← SYLLABUS</button><div class="grid grid-2" style="margin-top:16px"><section class="card"><div class="card-title"><h2>UNDERSTAND THE TOPIC</h2><span class="tag">${status.tested ? "TESTED" : status.practiced ? "PRACTICED" : status.learned ? "LEARNED" : "NEW"}</span></div><p>${simple}</p><h3>IMPORTANT DEFINITION</h3><p>${definition}</p><h3>FORMULA / KEY POINT</h3><p class="accent">${formula}</p><h3>EXAMPLE</h3><p>Write the given values and unit first. Apply the correct rule or formula, then show every step clearly.</p><h3>EXAM FOCUS</h3><p>Revise the definition, formula or rule, one example, and one common mistake.</p><div class="notice">1-minute revision: meaning → key point → example → one question.</div></section><section class="card"><h2>VIDEO RESOURCE</h2><p>A verified direct video is not configured for this exact topic yet. The app does not invent a URL; use the safe Hindi search below.</p><a class="btn secondary" href="${youtube(`${subjectName} ${topic} diploma Hindi`)}" target="_blank" rel="noopener noreferrer">SEARCH HINDI VIDEO ↗</a><h2 style="margin-top:20px">PRACTICE</h2><p>Write one definition, recall the key point, and solve one example before recording practice.</p><button class="btn secondary" data-action="exam-practice">MARK PRACTICED</button></section></div><section class="card" style="margin-top:16px"><div class="card-title"><h2>TOPIC TEST</h2><span class="tag">LEARNED → PRACTICED → TESTED</span></div><p>${question}</p><form id="examTestForm" style="display:flex;gap:8px"><input id="examAnswer" placeholder="Type your answer" required><button class="btn">CHECK ANSWER</button></form><div id="examTestResult"></div><button class="btn secondary" data-action="mark-learned" style="margin-top:14px">MARK LEARNED + SCHEDULE DAY 1</button></section>`);
}
function progressBar(value) { return `<div class="progress-track"><i style="width:${value}%"></i></div>`; }
function layout(title, subtitle, body, action = "") { return `<div class="page-head"><div><p class="eyebrow">// ${title.toUpperCase()}</p><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>${body}`; }
function youtube(query) { return `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`; }
const videoResources = {
  "Differential calculus": { title: "Derivatives | Easy Trick to Learn Important Formulae", channel: "Pradeep Giri Academy", duration: "13:20", url: "https://www.youtube.com/watch?v=-296435dMfk" }
};
function enhanceExamResources() {
  return;
}
function applyVideoResource() {
  if (!state.topic || !videoResources[state.topic]) return;
  const video = videoResources[state.topic];
  const heading = [...document.querySelectorAll("#content h2")].find(item => item.textContent === "VIDEO RESOURCE");
  const card = heading?.closest("section");
  if (!card) return;
  card.innerHTML = `<h2>VIDEO RESOURCE</h2><p><strong>${video.title}</strong><br>Channel: ${video.channel}<br>Duration: ${video.duration}<br>One focused Hindi diploma lecture, not a playlist.</p><a class="btn secondary" href="${video.url}" target="_blank" rel="noopener noreferrer">WATCH VIDEO ↗</a><h2 style="margin-top:20px">PRACTICE</h2><p>Write one definition, recall the key point, and solve one example before recording practice.</p><button class="btn secondary" data-action="exam-practice">MARK PRACTICED</button>`;
}
function renderHome() {
  const done = state.checked.length;
  const next = nextExamMission();
  const examAverage = Math.round(subjects.reduce((total, subject) => total + subjectProgress(subject), 0) / subjects.length);
  return layout("Learning command center", "One clear next step, every day. Your missions remain separate so focus stays sharp.", `
    <section class="card hero"><p class="eyebrow">SYSTEM STATUS: ONLINE</p><div class="big-status">WHAT SHOULD I STUDY NEXT?</div><p><span class="accent">RECOMMENDED:</span> ${next.subject} // ${next.topic}</p><div class="hero-actions"><button class="btn" data-action="continue">CONTINUE LEARNING →</button><button class="btn secondary" data-view="planner">BUILD TODAY'S PLAN</button></div></section>
    <div class="grid grid-3" style="margin-bottom:16px"><div class="card"><div class="stat">${state.settings.dailyTime === "2 hours" ? "02:00" : state.settings.dailyTime.replace(" hours", ":00").replace(" hour", ":00")}</div><div class="stat-label">TIME TARGET TODAY</div></div><div class="card"><div class="stat">${done} / 5</div><div class="stat-label">MISSION ITEMS DONE</div></div><div class="card"><div class="stat">${state.xp.toLocaleString()}</div><div class="stat-label">TOTAL XP</div></div></div>
    <div class="grid grid-2" style="margin-bottom:16px"><section class="card mission-card exam"><div class="mission-icon">🎓</div><h2>BACK EXAMS</h2><p>Four subjects // ${examAverage}% evidence-based progress</p><button class="btn secondary" data-view="exams">OPEN EXAM MISSION</button></section><section class="card mission-card career"><div class="mission-icon">⌘</div><h2>CAREER DEVELOPMENT</h2><p>15 levels // Python backend track active</p><button class="btn secondary" data-view="career">OPEN CAREER MISSION</button></section></div>
    <div class="split"><section class="card"><div class="card-title"><h2>TODAY'S MISSION</h2><span class="tag">${done} / 5 DONE</span></div><ul class="checklist">${["Physics — Laws & Concepts", "Mathematics — Integration", "Python — Functions", "20-minute revision", "Daily quiz"].map((x, i) => `<li><input type="checkbox" data-check="${i}" ${state.checked.includes(i) ? "checked" : ""}> ${x}</li>`).join("")}</ul></section><section class="card"><div class="card-title"><h2>QUICK SIGNALS</h2><span class="tag warn">LIVE</span></div><p>Next revision due: <strong class="accent">Physics // Motion</strong></p><p>Weak area: <strong class="exam-color">Mathematics // Integration</strong></p><p>Upcoming: <strong>${state.settings.examDate || "Back exam date not set"}</strong></p></section></div>`);
}
function subjectDetail(name) {
  const subject = subjects.find(s => s.name === name);
  return layout(subject.name, "Beginner-friendly notes, practice, revision, and live resource search.", `<button class="btn secondary" data-view="exams">← ALL SUBJECTS</button><div class="grid grid-2" style="margin-top:16px"><section class="card"><div class="card-title"><h2>TOPIC QUEUE</h2><span class="tag">${subject.progress}% COMPLETE</span></div><div class="lesson-list">${subject.topics.map((topic, i) => `<div class="lesson"><span class="num">${String(i + 1).padStart(2, "0")}</span><span><strong>${topic}</strong><small class="topic-note">General study guidance</small></span><span class="priority ${i === 0 ? "high" : i === 1 ? "medium" : "low"}">${i === 0 ? "MUST LEARN" : i === 1 ? "SHOULD LEARN" : "LOW PRIORITY"}</span><button class="btn secondary" data-action="topic" data-topic="${topic}" data-subject="${name}" style="margin-left:auto;padding:5px 7px">STUDY</button></div>`).join("")}</div></section><section class="card"><div class="card-title"><h2>SYLLABUS STATUS</h2><span class="tag warn">VERIFY</span></div><p>No official syllabus is embedded until it has been checked against the current BTEUP document. The queue beside this panel is a general learning scaffold, not an official unit or chapter list.</p><a class="btn" href="${youtube(subject.query)}" target="_blank" rel="noopener noreferrer">SEARCH CURRENT RESOURCES ↗</a><a class="btn secondary" href="${youtube(`${name} solved numericals Hindi`)}" target="_blank" rel="noopener noreferrer" style="margin-left:8px">NUMERICALS ↗</a><div class="notice" style="margin-top:18px">Priority labels are study guidance, not claims about frequency in exams. Verify the current syllabus and papers with official BTEUP sources.</div></section></div><div class="grid grid-3" style="margin-top:16px"><section class="card"><h2>LEARN</h2><p>Concept → why it matters → example → checkpoint.</p></section><section class="card"><h2>PRACTICE</h2><p>Do 3–10 questions before calling a topic practiced.</p></section><section class="card"><h2>TEST</h2><p>Mastery requires demonstrated performance, not completion.</p></section></div>`);
}
function renderExams() {
  const cards = subjects.map(s => { const progress = subjectProgress(s); return `<article class="card subject-card"><div class="card-title"><span class="tag">BTEUP TRACK</span><span class="exam-color">${s.icon}</span></div><h3>${s.name}</h3><p>Study queue // verify sources</p>${progressBar(progress)}<div class="subject-meta">${progress}% evidence-based <button class="btn secondary" style="float:right;padding:5px 7px" data-action="open-subject" data-subject="${s.name}">OPEN</button></div></article>`; }).join("");
  return layout("Back Exam Mission", "Beginner-friendly preparation for BTEUP first-year back exams.", `<div class="notice" style="margin-bottom:16px">Verification mode: use official BTEUP sources for the current syllabus, exam dates, and previous-year papers.</div><div class="grid grid-2" style="margin-bottom:16px">${cards}</div><div class="grid grid-3"><section class="card"><h2>7-DAY PLAN</h2><p>Build a balanced plan from the remaining syllabus, weak areas, and available time.</p><button class="btn secondary" data-view="planner">BUILD PLAN</button></section><section class="card"><h2>RESOURCE SEARCH</h2><p>Find Hindi/Hinglish lessons for every subject.</p><a class="btn secondary" href="${youtube("BTEUP first year diploma back exam preparation Hindi")}" target="_blank" rel="noopener noreferrer">SEARCH YOUTUBE ↗</a></section><section class="card"><h2>PRACTICE TEST</h2><p>Practice under exam conditions and identify weak topics.</p><button class="btn secondary" data-view="practice">START TEST</button></section></div>`);
}
function renderCareer() {
  if (state.careerLesson !== undefined) return renderCareerLesson(state.careerLesson);
  const lessons = careerLessons.map((lesson, i) => `<button class="lesson ${state.completedLessons.includes(i) ? "done" : ""}" data-action="lesson" data-lesson="${i}"><span class="num">${String(i + 1).padStart(2, "0")}</span>${lesson.title}<span class="priority ${state.completedLessons.includes(i) ? "low" : "medium"}">${state.completedLessons.includes(i) ? "LEARNED" : i > 0 && !state.completedLessons.includes(i - 1) ? "LOCKED" : "OPEN"}</span></button>`).join("");
  const projectCards = careerProjects.map((project, i) => `<article class="card"><span class="tag ${i === 2 ? "warn" : ""}">${project.difficulty}</span><h3 style="margin-top:16px">${project.name}</h3><p>${project.purpose}</p><p><strong>Skills:</strong> ${project.skills}</p><button class="btn secondary" data-action="project" data-project="${i}">OPEN BRIEF</button></article>`).join("");
  return layout("Career development", "CAREER SYSTEM ONLINE // Foundation → Python → Backend → Projects → AI → Internship.", `<section class="card hero"><p class="eyebrow">CURRENT TARGET</p><div class="big-status">PYTHON BACKEND + AI</div><p><span class="accent">NEXT STEP:</span> ${state.completedLessons.length < 9 ? careerLessons[state.completedLessons.length].title : "Complete the Python checkpoint"}</p><div class="hero-actions"><button class="btn" data-action="next-career">OPEN NEXT LESSON →</button><button class="btn secondary" data-action="career-plan">BUILD CAREER PLAN</button></div></section>
    <section class="card" style="margin-bottom:16px"><div class="card-title"><h2>ROADMAP // 15 LEVELS</h2><span class="tag">DSA RUNS ALONGSIDE DEVELOPMENT</span></div><div class="roadmap">${careerLevels.map((level, i) => `<button class="roadmap-step roadmap-button ${i < state.careerDone ? "roadmap-done" : i === state.careerDone ? "roadmap-current" : ""}" data-action="roadmap" data-level="${i}"><small>LEVEL ${String(i + 1).padStart(2, "0")}</small><h3>${level.name}</h3><p>${i < state.careerDone ? "✓ complete" : i === state.careerDone ? "● current focus" : "locked until prerequisites"}</p>${level.alongside ? `<small class="topic-note">${level.alongside}</small>` : ""}</button>`).join("")}</div></section>
    <div class="split"><section class="card"><div class="card-title"><h2>PYTHON LESSONS</h2><span class="tag">${state.completedLessons.length} / ${careerLessons.length} LEARNED</span></div><div class="lesson-list">${lessons}</div></section><section class="card"><div class="card-title"><h2>CAREER DECISION ENGINE</h2><span class="tag">ONE NEXT STEP</span></div><p>Recommendation: complete the next Python lesson before Flask. Backend frameworks depend on functions, modules, OOP, and HTTP basics.</p><div class="notice">LEARNED ≠ PRACTICED ≠ MASTERED</div><button class="btn" data-action="checkpoint" style="margin-top:18px">RUN PYTHON CHECKPOINT</button><a class="btn secondary" href="${youtube("Python backend beginner Hindi playlist")}" target="_blank" rel="noopener noreferrer" style="margin:18px 0 0 8px">SEARCH YOUTUBE ↗</a></section></div>
    <section class="card" style="margin-top:16px"><div class="card-title"><h2>PROJECT PROGRESSION</h2><span class="tag">BUILD TO PROVE</span></div><div class="grid grid-3">${projectCards}</div></section>
    <div class="grid grid-2" style="margin-top:16px"><section class="card"><div class="card-title"><h2>JOB READINESS</h2><span class="tag">NO GUARANTEES</span></div>${[["Python",40],["SQL",20],["Backend",10],["Projects",5],["DSA",15],["Interview",5]].map(([n,v]) => `<div class="bar-row"><label>${n}</label>${progressBar(v)}<strong>${v}%</strong></div>`).join("")}</section><section class="card"><h2>PREREQUISITE ENGINE</h2><p>Flask requires Python basics, functions, modules, OOP, and HTTP basics. Do not jump ahead just because a framework is popular.</p><button class="btn secondary" data-action="flask-gate" style="margin-top:16px">CHECK FLASK ACCESS</button></section></div>
    ${state.careerGate ? `<section class="card" style="border-color:var(--red);margin-top:16px"><div class="card-title"><h2>ACCESS DENIED // ${state.gateTarget || "ADVANCED TOPIC"}</h2><span class="tag danger">NOT READY</span></div><p>You need to complete the missing prerequisite before learning this advanced topic.</p><ul class="checklist"><li>✓ Python basics</li><li>✓ Functions</li><li>✓ Modules</li><li>✗ OOP basics</li><li>✗ HTTP basics</li></ul><button class="btn" data-action="learn-prerequisite" style="margin-top:16px">LEARN PREREQUISITE</button></section>` : ""}`);
}
function renderCareerLesson(index) {
  const lesson = careerLessons[index];
  const complete = state.completedLessons.includes(index);
  return layout(`Lesson ${String(index + 1).padStart(2, "0")} — ${lesson.title}`, "Learn → practice → prove → revise → choose the next step.", `<button class="btn secondary" data-action="close-lesson">← CAREER DASHBOARD</button><div class="grid grid-2" style="margin-top:16px"><section class="card"><h2>LEARN</h2><p>${lesson.learn}</p><h2>WHY</h2><p>${lesson.why}</p><h2>EXAMPLE</h2><p>${lesson.example}</p><h2>REVISION</h2><p>Day 0 learn → Day 1 recall → Day 3 practice → Day 7 test → Day 14 revision.</p><h2>NEXT STEP</h2><p class="accent">${lesson.next}</p></section><section class="card"><h2>CODE</h2><pre class="code-block">${lesson.code}</pre><h2>PRACTICE</h2><ul class="checklist">${lesson.practice.map(item => `<li>▸ ${item}</li>`).join("")}</ul><h2 style="margin-top:18px">MINI TASK</h2><p>${lesson.task}</p></section></div><section class="card" style="margin-top:16px"><div class="card-title"><h2>CHECKPOINT // LEARNED ≠ PRACTICED ≠ MASTERED</h2><span class="tag">${complete ? "LEARNED" : "NOT COMPLETED"}</span></div><p>Try the practice without copying. Your checkpoint evidence should show that you can explain and apply the concept.</p><button class="btn" data-action="complete-lesson" data-lesson="${index}">${complete ? "LESSON COMPLETED" : "MARK LEARNED + SCHEDULE REVISION"}</button><a class="btn secondary" href="${youtube(`${lesson.title} Python beginner Hindi`)}" target="_blank" rel="noopener noreferrer" style="margin-left:8px">SEARCH YOUTUBE ↗</a></section>`);
}
function renderTutor() {
  return layout("AI tutor", "Ask for a simpler explanation, a hint, a quiz, or a revision plan. Practice uses hint → explanation → solution.", `<div class="split"><section class="card chat"><div class="card-title"><h2>TUTOR SESSION // READY</h2><span class="tag">HINGLISH OK</span></div><div class="chat-log" id="chatLog"><div class="bubble">Hi! I am your study tutor. Tell me what is confusing, or ask: <strong>"Mera test lo"</strong>.<br><span class="muted">I will start from the simplest prerequisite.</span></div></div><form class="chat-form" id="chatForm"><input id="chatInput" placeholder="e.g. Integration easy way me samjhao..." required><button class="btn">SEND</button></form></section><section class="card"><h2>TUTOR COMMANDS</h2><div class="lesson-list"><button class="lesson" data-prompt="Mera test lo">▸ Take a test</button><button class="lesson" data-prompt="Give me a hint for integration">▸ Give me a hint</button><button class="lesson" data-prompt="Create revision notes">▸ Create revision notes</button><button class="lesson" data-prompt="Kal exam hai">▸ Emergency revision mode</button></div><div class="notice" style="margin-top:18px">This offline tutor is a guided demo. Connect a secure backend before sending private data to an AI provider.</div></section></div>`);
}
function renderPractice() {
  const q = questions[state.stats.solved % questions.length];
  return layout("Practice engine", "Difficulty adapts gradually. Start with a hint, submit an answer, then reveal the explanation.", `<div class="grid grid-3" style="margin-bottom:16px"><div class="card"><div class="stat">${state.stats.solved}</div><div class="stat-label">QUESTIONS SOLVED</div></div><div class="card"><div class="stat">${Math.round((state.stats.correct / Math.max(state.stats.solved, 1)) * 100)}%</div><div class="stat-label">ACCURACY</div></div><div class="card"><div class="stat">03</div><div class="stat-label">WEAK TOPICS</div></div></div><section class="card"><div class="card-title"><h2>BEGINNER CHECKPOINT</h2><span class="tag">QUESTION ${state.stats.solved + 1}</span></div><h3>${q.question}</h3><p id="hintText" class="muted">Need a nudge? Click hint before viewing the explanation.</p><button class="btn secondary" data-action="hint">SHOW HINT</button><form id="answerForm" style="margin-top:18px;display:flex;gap:8px"><input id="answerInput" placeholder="Type your answer" required><button class="btn">CHECK</button></form><div id="answerResult"></div></section>`);
}
function renderProjects() {
  const selected = Number.isInteger(state.project) ? careerProjects[state.project] : null;
  return layout("Project lab", "Build → test → document → publish. Projects prove what lessons cannot.", `<div class="grid grid-3">${careerProjects.map((project, i) => `<section class="card"><span class="tag ${i === 2 ? "warn" : ""}">${project.difficulty}</span><h2 style="margin-top:16px">${project.name}</h2><p>${project.purpose}</p><p><strong>Skills:</strong> ${project.skills}</p><button class="btn ${i ? "secondary" : ""}" data-action="project" data-project="${i}">OPEN PROJECT BRIEF</button></section>`).join("")}<section class="card"><span class="tag danger">LOCKED</span><h2 style="margin-top:16px">AI STUDY ASSISTANT</h2><p>Unlock after backend and API checkpoints. Calling an AI API is not the same as training a model.</p><button class="btn secondary" data-action="notify">ACCESS DENIED</button></section></div>${selected ? `<section class="card" id="projectBrief" style="margin-top:16px"><h2>${selected.name.toUpperCase()} // BRIEF</h2><p><strong>PURPOSE:</strong> ${selected.purpose}</p><p><strong>FEATURES:</strong> ${selected.features}</p><pre class="code-block">${selected.folder}</pre><p><strong>TESTING:</strong> Test the core behavior, invalid input, and one edge case before publishing.</p><p><strong>GITHUB:</strong> Create a repository, add a README with setup, usage, screenshots, and learning notes.</p><p><strong>RESUME:</strong> Built ${selected.name} using ${selected.skills}; implemented a working feature set with tests and documentation.</p><p><strong>NEXT IMPROVEMENT:</strong> ${selected.next}</p><button class="btn" data-action="mark-project">MARK MILESTONE COMPLETE</button></section>` : ""}`);
}
function renderProgress() {
  const exam = subjects.map(s => `<div class="bar-row"><label>${s.name}</label>${progressBar(s.progress)}<strong>${s.progress}%</strong></div>`).join("");
  const pythonProgress = Math.round((state.completedLessons.length / careerLessons.length) * 100);
  const practiceAccuracy = Math.round((state.stats.correct / Math.max(state.stats.solved, 1)) * 100);
  const career = [["C", 80], ["Python", pythonProgress], ["Git / GitHub", state.careerDone >= 2 ? 40 : 0], ["SQL", state.careerDone >= 3 ? 30 : 0], ["Backend", state.careerDone >= 7 ? 20 : 0], ["Projects", Math.min((state.projectMilestones || 0) * 20, 100)], ["AI Integration", state.careerDone >= 10 ? 10 : 0]].map(([n, v]) => `<div class="bar-row"><label>${n}</label>${progressBar(v)}<strong>${v}%</strong></div>`).join("");
  return layout("Progress telemetry", "Evidence dashboard: completion, practice, projects, weak areas, revision, and readiness.", `<div class="grid grid-2"><section class="card"><div class="card-title"><h2>CAREER PROGRESS</h2><span class="tag">ACTIVE</span></div>${career}</section><section class="card"><div class="card-title"><h2>JOB READINESS // NO GUARANTEES</h2><span class="tag">EVIDENCE ONLY</span></div>${[["Python", pythonProgress],["SQL", state.careerDone >= 3 ? 30 : 0],["Backend", state.careerDone >= 7 ? 20 : 0],["Projects", Math.min((state.projectMilestones || 0) * 20, 100)],["DSA", 15],["Interview", 5]].map(([n, v]) => `<div class="bar-row"><label>${n}</label>${progressBar(v)}<strong>${v}%</strong></div>`).join("")}</section></div><div class="grid grid-3" style="margin-top:16px"><div class="card"><div class="stat">${state.completedLessons.length}</div><div class="stat-label">LESSONS COMPLETED</div></div><div class="card"><div class="stat">${state.stats.solved} / ${practiceAccuracy}%</div><div class="stat-label">PRACTICE / ACCURACY</div></div><div class="card"><div class="stat">${state.stats.practiceMinutes}m</div><div class="stat-label">PRACTICE TIME</div></div></div><div class="grid grid-2" style="margin-top:16px"><section class="card"><h2>WEAK AREAS</h2><p>${state.stats.weak.length ? state.stats.weak.join(" // ") : "None identified yet."}</p></section><section class="card"><h2>REVISION DUE</h2><p>${state.revision.length} spaced-recall item(s) queued. <button class="btn secondary" data-view="revision" style="padding:5px 7px">OPEN QUEUE</button></p></section></div>`);
}
function renderRevision() {
  const items = state.revision.length ? state.revision.map(item => `<div class="lesson"><span class="num">${item.date}</span>${item.topic}<button class="btn secondary" data-action="complete-revision" data-topic="${item.topic}" style="margin-left:auto;padding:5px 7px">DONE</button></div>`).join("") : `<div class="notice">No revision is queued yet. Complete a topic from a subject workspace to schedule Day 1, Day 3, Day 7, and Day 14 recall.</div>`;
  return layout("Spaced revision", "The system schedules recall so learning survives beyond one study session.", `<section class="card" style="margin-bottom:16px"><div class="card-title"><h2>REVISION MODES</h2><span class="tag">CHOOSE A WINDOW</span></div><div class="grid grid-3"><button class="lesson" data-action="revision-mode" data-mode="7-DAY">🔥 7-DAY REVISION<small>Balanced coverage + breaks</small></button><button class="lesson" data-action="revision-mode" data-mode="3-DAY">🔥 3-DAY REVISION<small>High-priority material</small></button><button class="lesson" data-action="revision-mode" data-mode="1-DAY">🔥 1-DAY REVISION<small>Recall, formulas, questions</small></button></div><div id="revisionModeOutput" class="notice" style="margin-top:16px">Select a window to see a realistic focus plan.</div></section><section class="card"><div class="card-title"><h2>REVISION QUEUE</h2><span class="tag">${state.revision.length} DUE</span></div><div class="lesson-list">${items}</div></section>`);
}
function renderPlanner() {
  return layout("Adaptive daily planner", "Tell the system how much time you have. It balances exam urgency and career momentum.", `<section class="card"><h2>HOW MUCH TIME CAN YOU STUDY TODAY?</h2><div class="grid grid-3" style="margin:18px 0">${["30 minutes", "1 hour", "2 hours", "3 hours", "4+ hours"].map(t => `<button class="lesson" data-time="${t}">▸ ${t}</button>`).join("")}</div><div id="planOutput"><div class="notice">Choose a time budget to generate a realistic plan with breaks.</div></div></section>`);
}
function renderSettings() {
  const s = state.settings;
  return layout("Settings", "Tune the learning engine to your reality.", `<section class="card"><div class="form-row"><div><label>LANGUAGE</label><select id="settingLanguage"><option ${s.language === "English" ? "selected" : ""}>English</option><option ${s.language === "Hindi" ? "selected" : ""}>Hindi</option><option ${s.language === "Hinglish" ? "selected" : ""}>Hinglish</option></select></div><div><label>DAILY STUDY TIME</label><select id="settingTime"><option>30 minutes</option><option>1 hour</option><option ${s.dailyTime === "2 hours" ? "selected" : ""}>2 hours</option><option>3 hours</option><option>4+ hours</option></select></div><div><label>CAREER GOAL</label><input id="settingGoal" value="${s.goal}"></div><div><label>NEXT EXAM DATE</label><input id="settingExam" type="date" value="${s.examDate}"></div></div><div style="margin-top:18px"><label><input type="checkbox" checked style="width:auto"> Revision reminders</label><label><input type="checkbox" checked style="width:auto"> Daily mission notification</label></div><button class="btn" data-action="save-settings">SAVE SETTINGS</button></section><section class="card" style="margin-top:16px"><h2>DATA</h2><p>Your progress is stored locally in this browser. No API keys are displayed or stored in the client.</p><button class="btn secondary" data-action="export">EXPORT PROGRESS</button><button class="btn secondary" data-action="reset" style="margin-left:8px">RESET PROGRESS</button></section>`);
}
function subjectDetail(name) {
  const subject = subjects.find(s => s.name === name); const progress = subjectProgress(subject);
  return layout(subject.name, "Topic → notes → practice → test → revision.", `<button class="btn secondary" data-view="exams">← ALL SUBJECTS</button><div class="grid grid-2" style="margin-top:16px"><section class="card"><div class="card-title"><h2>TOPIC LIST</h2><span class="tag">${progress}% PROGRESS</span></div><div class="lesson-list">${subject.topics.map((topic, i) => { const s = topicStatus(name, topic); const statusLabel = s.tested ? "TESTED" : s.practiced ? "PRACTICED" : s.learned ? "LEARNED" : "START"; return `<div class="lesson"><span class="num">${String(i + 1).padStart(2,"0")}</span><span><strong>${topicLabel(topic)}</strong><small class="topic-note">${statusLabel} · notes → practice → test</small></span><button class="btn secondary" data-action="topic" data-topic="${topic}" data-subject="${name}" style="margin-left:auto;padding:5px 7px">OPEN</button></div>`; }).join("")}</div></section><section class="card"><h2>LAST-MINUTE REVISION</h2><p>After recording progress, choose a 7-day, 3-day, or 1-day revision mode.</p><button class="btn secondary" data-view="revision">OPEN REVISION</button><div class="notice" style="margin-top:18px">Confirm the official BTEUP unit and chapter mapping with the current board document.</div></section></div>`);
}
const views = { home: renderHome, exams: renderExams, career: renderCareer, tutor: renderTutor, practice: renderPractice, projects: renderProjects, progress: renderProgress, planner: renderPlanner, settings: renderSettings, revision: renderRevision };
function render(view = state.view) {
  state.view = views[view] ? view : "home";
  document.querySelector("#content").innerHTML = state.topic ? renderExamTopic(state.subject, state.topic) : state.subject ? subjectDetail(state.subject) : views[state.view]();
  applyVideoResource();
  document.querySelectorAll(".nav-item").forEach(b => b.classList.toggle("active", b.dataset.view === state.view));
  bindInteractions();
  const xp = document.querySelector("#xpValue"); if (xp) xp.textContent = state.xp.toLocaleString();
}
function toast(message) { const el = document.querySelector("#toast"); el.textContent = message; el.classList.add("show"); setTimeout(() => el.classList.remove("show"), 2600); }
function tutorReply(message) {
  const lower = message.toLowerCase();
  if (lower.includes("test")) return "I will start with a beginner checkpoint. First question: what is a function, and why would you use one? Reply in your own words.";
  if (lower.includes("samajh") || lower.includes("easy")) return "Chalo prerequisite se start karte hain: function ek reusable box hai. Input do, kaam karao, output lo. Pehle ek greeting function likho.";
  if (lower.includes("galat") || lower.includes("wrong")) return "Mistake ko isolate karo: expected input, actual input, aur har step ka output check karo. Exact code bhejo, main line-by-line hint dunga.";
  if (lower.includes("project")) return `Project choose karne se pehle skill check: Python functions, files, exceptions, and Git. Abhi safest next build is "${careerProjects[0].name}".`;
  if (lower.includes("hint")) return "HINT: Break the problem into the smallest known step. What formula or prerequisite does the question depend on?";
  if (lower.includes("exam")) return "EMERGENCY MODE: Start with formulas and definitions, then solve two representative questions. Keep the final 20 minutes for recall, not new topics.";
  if (lower.includes("revision")) return "REVISION NOTE: Learn on Day 0, quick recall on Day 1, practice on Day 3, test on Day 7, then revisit on Day 14.";
  return "Let's simplify it. Tell me the exact step where you get stuck, and I will explain the prerequisite first.";
}
function bindInteractions() {
  document.querySelectorAll("[data-view]").forEach(el => el.addEventListener("click", () => { state.subject = null; state.topic = null; render(el.dataset.view); closeMenu(); }));
  document.querySelectorAll("[data-check]").forEach(el => el.addEventListener("change", () => { const i = Number(el.dataset.check); state.checked = el.checked ? [...new Set([...state.checked, i])] : state.checked.filter(x => x !== i); state.xp += el.checked ? 10 : 0; save(); render("home"); }));
  document.querySelectorAll("[data-action]").forEach(el => el.addEventListener("click", () => {
    const action = el.dataset.action;
    if (action === "continue") { const next = nextExamMission(); state.subject = next.subject; state.topic = next.topic; save(); render("exams"); toast(`Current exam lesson loaded: ${next.subject} // ${next.topic}`); }
    if (action === "next-career") { state.careerLesson = state.completedLessons.length < careerLessons.length ? state.completedLessons.length : careerLessons.length - 1; render("career"); }
    if (action === "close-lesson") { delete state.careerLesson; render("career"); }
    if (action === "complete-lesson") { const i = Number(el.dataset.lesson); if (!state.completedLessons.includes(i)) { state.completedLessons.push(i); state.careerDone = Math.max(state.careerDone, Math.min(i + 1, careerSteps.length)); state.xp += 25; const topic = `Python // ${careerLessons[i].title}`; state.revision = [...state.revision.filter(item => item.topic !== topic), { topic, date: "DAY 1", due: ["DAY 1", "DAY 3", "DAY 7", "DAY 14"] }]; } delete state.careerLesson; save(); render("career"); toast("Lesson learned. Spaced revision scheduled."); }
    if (action === "career-plan") { render("planner"); toast("Choose your available time for a focused career mission."); }
    if (action === "ai-gate") { toast(state.completedLessons.length >= 13 ? "AI integration gate is open." : "ACCESS DENIED: finish Python, HTTP, and backend prerequisites first."); }
    if (action === "flask-gate") { state.careerGate = true; render("career"); }
    if (action === "learn-prerequisite") { state.careerLesson = Number.isInteger(state.gateLesson) ? state.gateLesson : 12; delete state.careerGate; delete state.gateTarget; delete state.gateLesson; render("career"); }
    if (action === "notify") toast("Plan queued. Keep it realistic and take breaks.");
    if (action === "open-subject") { state.subject = el.dataset.subject; state.topic = null; render("exams"); }
    if (action === "topic") { state.subject = el.dataset.subject; state.topic = el.dataset.topic; save(); render("exams"); }
    if (action === "back-subject") { state.topic = null; render("exams"); }
    if (action === "mark-learned") { const key = topicKey(state.subject, state.topic); state.examTopics[key] = { ...topicStatus(state.subject, state.topic), learned:true }; state.revision = [...state.revision.filter(item => item.topic !== `${state.subject} // ${state.topic}`), { topic:`${state.subject} // ${state.topic}`, date:"DAY 1", due:["DAY 1", "DAY 3", "DAY 7", "DAY 14"] }]; state.xp += 10; save(); render("exams"); toast("Learned recorded. Day 1 revision scheduled."); }
    if (action === "exam-practice") { const key = topicKey(state.subject, state.topic); state.examTopics[key] = { ...topicStatus(state.subject, state.topic), learned:true, practiced:true }; state.stats.practiceMinutes += 10; save(); render("exams"); toast("Practice recorded. Take the topic test next."); }
    if (action === "checkpoint") toast("Checkpoint started. Mastery requires demonstrated understanding.");
    if (action === "lesson") { const lessonIndex = Number(el.dataset.lesson); if (lessonIndex > 0 && !state.completedLessons.includes(lessonIndex - 1)) { state.careerGate = true; state.gateTarget = careerLessons[lessonIndex].title; state.gateLesson = lessonIndex - 1; render("career"); toast(`ACCESS DENIED: complete "${careerLessons[lessonIndex - 1].title}" first.`); } else { state.careerLesson = lessonIndex; render("career"); } }
    if (action === "roadmap") { const level = Number(el.dataset.level); if (level > state.careerDone && level !== 8) { state.careerGate = true; state.gateTarget = careerLevels[level].name; delete state.gateLesson; render("career"); toast(`ACCESS DENIED: complete ${careerLevels[level].prerequisite} first.`); } else { toast(level === 8 ? "DSA unlocked alongside development. Keep building projects." : `Level ${String(level + 1).padStart(2, "0")} selected.`); } }
    if (action === "hint") document.querySelector("#hintText").textContent = questions[state.stats.solved % questions.length].hint;
    if (action === "complete-revision") { const item = state.revision.find(x => x.topic === el.dataset.topic); if (item?.due?.length > 1) { state.revision = state.revision.map(x => x.topic === el.dataset.topic ? { ...x, date:x.due[1], due:x.due.slice(1) } : x); } else { state.revision = state.revision.filter(x => x.topic !== el.dataset.topic); } state.xp += 15; state.stats.practiceMinutes += 10; save(); render("revision"); toast("Revision completed. Next recall scheduled."); }
    if (action === "revision-mode") { const plans = { "7-DAY": "Days 1–4: one exam subject block + one weak-topic practice block. Days 5–6: mixed questions. Day 7: timed test and error review. Take a 10-minute break between blocks.", "3-DAY": "Day 1: formulas and definitions. Day 2: high-priority examples and practice. Day 3: timed mock, then revise only wrong answers. Take a 10-minute break between blocks.", "1-DAY": "Formulas → definitions → important concepts → selected questions → short notes. Study in 40-minute blocks with 10-minute breaks; stop new topics before the final recall block." }; document.querySelector("#revisionModeOutput").textContent = plans[el.dataset.mode]; }
    if (action === "project") { state.project = Number(el.dataset.project); render("projects"); }
    if (action === "mark-project") { state.projectMilestones = (state.projectMilestones || 0) + 1; state.xp += 50; save(); toast("Project milestone recorded."); }
    if (action === "save-settings") { state.settings = { ...state.settings, language: document.querySelector("#settingLanguage").value, dailyTime: document.querySelector("#settingTime").value, goal: document.querySelector("#settingGoal").value, examDate: document.querySelector("#settingExam").value }; save(); render("settings"); toast("Settings saved locally."); }
    if (action === "export") { const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "studyos-progress.json"; a.click(); URL.revokeObjectURL(url); toast("Progress export downloaded."); }
    if (action === "reset") { localStorage.removeItem("studyOSState"); location.reload(); }
  }));
  document.querySelectorAll("[data-time]").forEach(el => el.addEventListener("click", () => {
    const plans = { "30 minutes": "20 min — Mathematics priority topic<br>10 min — Quick recall quiz", "1 hour": "30 min — Mathematics<br>20 min — Physics revision<br>10 min — Quiz", "2 hours": "45 min — Mathematics<br>35 min — Physics<br>25 min — Python<br>15 min — Revision", "3 hours": "60 min — Mathematics<br>45 min — Physics<br>45 min — Python<br>20 min — Revision<br>10 min — Quiz", "4+ hours": "90 min — Exam priority block<br>60 min — Second subject<br>60 min — Career lesson<br>30 min — Practice<br>20 min — Revision" };
    document.querySelector("#planOutput").innerHTML = `<div class="card" style="border-color:var(--green-dim)"><h2>TODAY'S MISSION // ${el.dataset.time.toUpperCase()}</h2><p>${plans[el.dataset.time]}</p><p class="accent">TOTAL: ${el.dataset.time} // BREAKS INCLUDED</p><button class="btn" data-action="notify">ACCEPT PLAN</button></div>`; bindInteractions();
  }));
  document.querySelectorAll("[data-prompt]").forEach(el => el.addEventListener("click", () => { document.querySelector("#chatInput").value = el.dataset.prompt; document.querySelector("#chatForm").requestSubmit(); }));
  const form = document.querySelector("#chatForm");
  if (form) form.addEventListener("submit", e => { e.preventDefault(); const input = document.querySelector("#chatInput"); const log = document.querySelector("#chatLog"); log.insertAdjacentHTML("beforeend", `<div class="bubble user">${input.value}</div><div class="bubble">${tutorReply(input.value)}</div>`); input.value = ""; log.scrollTop = log.scrollHeight; });
  const answerForm = document.querySelector("#answerForm");
  if (answerForm) answerForm.addEventListener("submit", e => { e.preventDefault(); const q = questions[state.stats.solved % questions.length]; const answer = document.querySelector("#answerInput").value.trim().toLowerCase(); const correct = answer === q.answer.toLowerCase(); state.stats.solved += 1; state.stats.correct += correct ? 1 : 0; state.stats.practiceMinutes += 5; if (!correct && !state.stats.weak.includes(q.question)) state.stats.weak.push(q.question); state.xp += correct ? 20 : 5; save(); document.querySelector("#answerResult").innerHTML = `<div class="notice" style="margin-top:15px">${correct ? "✓ CORRECT" : "✗ NOT YET"} — ${q.explanation}<br><span class="muted">${correct ? "Difficulty can increase gradually." : "Keep this concept in your revision queue before advancing."}</span></div><button class="btn secondary" data-view="practice" style="margin-top:10px">NEXT QUESTION</button>`; bindInteractions(); });
  const examForm = document.querySelector("#examTestForm");
  if (examForm) examForm.addEventListener("submit", e => { e.preventDefault(); const answer = document.querySelector("#examAnswer").value.trim().toLowerCase().replaceAll(" ", ""); const expected = (examAnswers[state.topic] || "review").toLowerCase().replaceAll(" ", ""); const correct = answer === expected; const key = topicKey(state.subject, state.topic); state.stats.solved += 1; state.stats.practiceMinutes += 5; if (correct) { state.stats.correct += 1; state.examTopics[key] = { ...topicStatus(state.subject, state.topic), learned:true, practiced:true, tested:true }; state.xp += 25; } else if (!state.stats.weak.includes(state.topic)) state.stats.weak.push(state.topic); save(); document.querySelector("#examTestResult").innerHTML = `<div class="notice" style="margin-top:15px">${correct ? "CORRECT — topic tested." : "NOT YET — review notes, then practice again."}</div>`; });
}
new MutationObserver(enhanceExamResources).observe(document.querySelector("#content"), { childList: true, subtree: true });
function closeMenu() { const sidebar = document.querySelector("#sidebar"); sidebar.classList.remove("open"); document.querySelector("#menuToggle").setAttribute("aria-expanded", "false"); }
document.querySelector("#menuToggle").addEventListener("click", () => { const sidebar = document.querySelector("#sidebar"); sidebar.classList.toggle("open"); document.querySelector("#menuToggle").setAttribute("aria-expanded", sidebar.classList.contains("open")); });
document.querySelector("#navBackdrop").addEventListener("click", closeMenu);
document.querySelector("#soundToggle").addEventListener("click", () => { state.settings.sound = !state.settings.sound; save(); updateSoundButton(); if (state.settings.sound) playStartupTone(); });
function updateSoundButton() { document.querySelector("#soundToggle").textContent = `SOUND: ${state.settings.sound ? "ON" : "OFF"}`; }
function playStartupTone() { try { const AC = window.AudioContext || window.webkitAudioContext; const ctx = new AC(); const oscillator = ctx.createOscillator(); const gain = ctx.createGain(); oscillator.frequency.value = 520; gain.gain.setValueAtTime(.025, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + .12); oscillator.connect(gain).connect(ctx.destination); oscillator.start(); oscillator.stop(ctx.currentTime + .12); } catch (_) {} }
updateSoundButton();
setInterval(() => { document.querySelector("#clock").textContent = new Date().toLocaleTimeString([], { hour12: false }); }, 1000);
render();
